#!/usr/bin/env node
// Measures gas scenarios in isolated mode and writes docs/GAS.md.
// Usage (from repo root or contracts/): node contracts/script/gas-report.mjs
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const contracts = resolve(dirname(fileURLToPath(import.meta.url)), "..");
execFileSync("forge", ["test", "--isolate", "--match-contract", "GasScenariosTest"], {
  cwd: contracts,
  env: { ...process.env, GAS_SNAPSHOT: "true" },
  stdio: "inherit",
});
const gas = JSON.parse(readFileSync(resolve(contracts, "snapshots/ArcDrawGas.json"), "utf8"));
const forgeVersion = execFileSync("forge", ["--version"], { encoding: "utf8" }).split("\n")[0];

// Arc gas price floor: 20 gwei, priced in native USDC (18 decimals). 1 gas * 20e9 wei = 2e-8 USDC.
const usdc = (g) => ((Number(g) * 20e9) / 1e18).toFixed(5);

const rows = [
  ["requestRandomness_noBounty", "`requestRandomness(0, 0)`, first request (requestCount 0 -> 1)"],
  ["requestRandomness_bounty", "`requestRandomness(100_000, 0.01 USDC)` incl. USDC transferFrom"],
  ["verifyRound_fresh", "`verifyRound` with a real quicknet signature (BLS verify + store + event)"],
  ["fulfill_freshRound_bounty_noCallback", "`fulfill`, fresh round, bounty paid, EOA requester"],
  ["fulfill_verifiedRound_bounty_noCallback", "`fulfill`, round already verified (signature omitted)"],
  ["fulfill_freshRound_bounty_fairAllocationCallback", "`fulfill`, fresh round, bounty, FairAllocation callback"],
  ["fulfillBatch_freshRound_5ids_bounty_noCallback", "`fulfillBatch`, fresh round, 5 ids, one bounty transfer"],
  ["refund_bounty", "`refund` after expiry, bounty returned"],
  ["fairAllocation_createSale_bounty", "FairAllocation `createSale` with 0.01 USDC bounty escrow"],
  ["fairAllocation_subscribe", "FairAllocation `subscribe` (second subscriber)"],
  ["fairAllocation_draw", "FairAllocation `draw` (approve + requestRandomness)"],
  ["fairAllocation_finalize_N5_K3", "FairAllocation `finalize`, N=5, K=3"],
  ["fairAllocation_claimRefund", "FairAllocation `claimRefund` (loser)"],
];

let md = `# Gas

> Generated by \`node contracts/script/gas-report.mjs\` (${forgeVersion}). Do not edit by hand.
> Every call runs as its own transaction (\`forge test --isolate\`): cold storage, 21k intrinsic gas and calldata included.
> Signatures are real drand quicknet beacons; BLS verification uses the EIP-2537 precompiles (Osaka EVM).
> USDC is a local 6-decimal mock with a blocklist, so USDC transfer costs differ slightly from Arc's USDC proxy.
> Cost column: Arc's 20 gwei floor, paid in USDC (1 gas = 0.00000002 USDC).

| Scenario | Gas | USDC at 20 gwei | Description |
|---|---:|---:|---|
`;
for (const [key, desc] of rows) {
  if (!(key in gas)) throw new Error(`missing gas scenario ${key}`);
  md += `| \`${key}\` | ${Number(gas[key]).toLocaleString("en-US")} | ${usdc(gas[key])} | ${desc} |\n`;
}
md += `
## Other measurements (non-isolated tests, see \`forge test -vv\`)

| Measurement | Gas | Source |
|---|---:|---|
| BLS verify only (spike harness) | 213,915 | \`test/spike/QuicknetVerify.t.sol\` |
| \`verifyRound\` on an Arc mainnet fork (block 21283310) | 235,588 | \`test/fork/ArcMainnetFork.t.sol\` (execution gas, no intrinsic) |
| FairAllocation \`finalize\`, N=1000, K=100 | 321,227 | \`test_gas_finalize_N1000_K100\` |
| FairAllocation \`finalize\`, N=1000, K=999 (worst case) | 1,064,913 | \`test_gas_finalize_N1000_K999\` |
| FairAllocation callback (\`rawFulfillRandomness\`, cold storage) | 33,994 of 60,000 budget | \`test_callbackGasIsEnough\` trace |

## Notes for relayers

- An **invalid** signature that passes the cheap encoding checks (compression flag, infinity flag, x < p) but is not a valid
  G1 point makes the EIP-2537 precompile fail, which consumes all gas forwarded to it (about 5M gas in the tests).
  Always verify the beacon offchain (\`verifyBeacon\` in the SDK) and simulate before sending.
- \`fulfill\` needs \`callbackGasLimit + callbackGasLimit/63 + 5,000\` gas left at the callback, otherwise it reverts with
  \`InsufficientGasForCallback\`. Estimate with \`eth_estimateGas\` and add headroom for the callback.
- \`.gas-snapshot\` (from \`forge snapshot\`) tracks per-test gas for regressions; this file tracks per-call costs.
`;
writeFileSync(resolve(contracts, "../docs/GAS.md"), md);
console.log("wrote docs/GAS.md");
